services:
  - type: web
    name: car-price-predictor
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn --chdir server app:app
    envVars:
      - key: PYTHON_VERSION

        value: 3.9.0
