services:
  - type: web
    name: car-price-predictor
    env: python
    plan: free
    buildCommand: cd Server && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --chdir Server app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

